[package]
name = "my_application"
version = "0.1.0"
edition = "2021"

[dependencies]
my_library = { path = "../my_library" }  # my_library
# my_library = "0.1"  # Replace with cargo.io published version